In [15]:
# Importaciones
import pandas as pd
import numpy as np

import sys 
sys.path.append('..')

from src import sp_limpieza as lp

In [16]:
# Leer los archivos
archivo1 = pd.read_excel("../data_raw/customer-details.xlsx", sheet_name='2012')
archivo2 = pd.read_excel("../data_raw/customer-details.xlsx", sheet_name='2013')
archivo3 = pd.read_excel("../data_raw/customer-details.xlsx", sheet_name='2014')

# Se concatenan los archivos al tener las mismas columnas
df_total_cd = pd.concat([archivo1, archivo2, archivo3], ignore_index=True)

In [17]:
df_total_cd.tail()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
43165,14085,156980,1,2,2014-05-17,7,5f432048-d515-4bb5-9c94-62db451f88d4
43166,14086,139820,0,0,2014-09-29,1,993bbbd6-4dbc-4a40-a408-f91f8462bee6
43167,14087,78470,2,2,2014-10-28,12,d6271666-319d-42c8-a741-cb22bf2c2093
43168,14088,144218,0,1,2014-07-01,9,f67fbfa8-6573-414d-a805-b26a2f1b1ceb
43169,14089,115155,0,2,2014-12-25,7,9727bc06-c11a-461a-a5bb-3d210467cc2a

In [18]:
df_total_cd.shape
print (f'El número de filas del conjunto de datos es : {df_total_cd.shape[0]}')
print (f'El número de columnas del conjunto de datos es : {df_total_cd.shape[1]}')

El número de filas del conjunto de datos es : 43170
El número de columnas del conjunto de datos es : 7

In [19]:
df_total_cd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[ns]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  object
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 2.3+ MB

In [20]:
# Crear un dataframe alternativo para trabajar
df_cust = df_total_cd.copy()

In [21]:
df_cust.columns

Index(['Unnamed: 0', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer',
       'NumWebVisitsMonth', 'ID'],
      dtype='object')

In [22]:
# Elimino la columna Unnamed al ser el índice generado automáticamente por pandas
df_cust.drop(columns="Unnamed: 0", inplace=True)
df_cust.tail(3)

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
43167,78470,2,2,2014-10-28,12,d6271666-319d-42c8-a741-cb22bf2c2093
43168,144218,0,1,2014-07-01,9,f67fbfa8-6573-414d-a805-b26a2f1b1ceb
43169,115155,0,2,2014-12-25,7,9727bc06-c11a-461a-a5bb-3d210467cc2a

In [23]:
df_cust = df_cust.rename(columns={'ID': 'Id'})
df_cust = df_cust.rename(columns={'NumWebVisitsMonth': 'Num_Web_Visits_Month'})

In [24]:
lp.eda_preliminar(df_cust)

,Income,Kidhome,Teenhome,Dt_Customer,Num_Web_Visits_Month,Id
32422,136832,1,1,2014-06-26,29,a9f57c9d-f0b5-4641-a260-8ec335a05546
40932,52177,2,0,2014-10-29,25,96acb6a2-035c-48f8-b90d-c90dcca24d21
15373,65764,1,1,2012-12-01,14,3d997f00-0f86-475a-9b33-2b37f6fafa91
3693,99907,1,2,2012-11-30,16,1df33bc9-2761-483b-ac6b-df9fe0bc2e94
12788,88990,0,2,2012-12-19,5,9e76438a-49a0-47fa-a04d-045aed905d11

-------------------------------------
INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Income                43170 non-null  int64
 1   Kidhome               43170 non-null  int64
 2   Teenhome              43170 non-null  int64
 3   Dt_Customer           43170 non-null  datetime64[ns]
 4   Num_Web_Visits_Month  43170 non-null  int64
 5   Id                    43170 non-null  object
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 2.0+ MB

None

-------------------------------------
NULOS

Income                  0.0
Kidhome                 0.0
Teenhome                0.0
Dt_Customer             0.0
Num_Web_Visits_Month    0.0
Id                      0.0
dtype: float64

-------------------------------------
DUPLICADOS

0

-------------------------------------
VALUE COUNTS
Id
089b39d8-e4d0-461b-87d4-814d71e0e079    1
38708e69-8996-4d51-956a-d422fd78872d    1
7218c062-4571-4fd9-8bad-c6a09ad1eb5d    1
853e4074-829e-47e4-9287-06b4cb0f814f    1
a185385b-b614-423b-9932-a132ed02eed1    1
                                       ..
8e1e500d-de2a-4e14-b027-20983ebaeeb9    1
bdee816d-7f9d-442a-99e1-cf259021f8f5    1
8d3ae2ee-5363-4508-ac65-cbecc78a08bb    1
4601e86a-18c4-473c-8467-fb16e838be7d    1
9727bc06-c11a-461a-a5bb-3d210467cc2a    1
Name: count, Length: 43170, dtype: int64
------------------------------------

In [25]:
df_cust.sample()

,Income,Kidhome,Teenhome,Dt_Customer,Num_Web_Visits_Month,Id
15971,168389,1,1,2012-02-15,18,2092e55d-ffca-4d75-b66e-dd7f544ab68c

In [26]:
# Guardo archivo
df_cust.to_excel("../data_processed/cd_modificaciones.xlsx", index=False)